### ISSUE TITLE
Reproducibility Software Session Information table fails to use GitHub Location

### ISSUE THREAD

**Issue by seajane** [FredHutch/VISCfunctions#61] opened 2020-09-08 21:28 UTC
**Issue:**

The "Reproducibility software session information" table of the report template has a section for "location". When there is a GitHub repo should link to that repo.  When there is not an external repo, this "location" is set to the local version of the repo.  Currently the feature that updates the local location with the GitHub repo location is not functioning properly.  

**Desired Behavior:**

The local repo location is replaced with the GitHub location, when one exists.

**Reproducible Example:**

1. Open RStudio
2. Navigate to a repo that is already on GitHub and is local. (Pantaleo.EV07 in the example case)
3. Type `remotes::install_github("FredHutch/VISCtemplates")` into the Console of RStudio and hit 'Return'
4. Type `library(VISCtemplates)` into the Console
5. Create_visc_project in your current project folder (e.g. "C:/Users/hbouzek/Documents/Pantaleo.EV07") by typing `create_visc_project("C:/Users/hbouzek/Documents/Pantaleo.EV07")`
6. At each prompt that asks if you wish to overwrite existing files type "3" for 'No'.
7. Do not commit the uncommitted files when prompted by "Is it ok to commit them?" by typing "3" and return.
8. Knit the new "Untitled" Rmarkdown document.
9. Check the Reproducibility software session information at the bottom of the report to confirm that the location is the location of the current project on your local drive.

**Screenshots:**
![image](https://user-images.githubusercontent.com/8787869/92529523-82a3df00-f1df-11ea-91ff-a6f902071f47.png)

**Conditions Under Which Error Occurred:**
Office or Home: Home
Fred Hutch or Home Computer: Fred Hutch laptop
OS: Microsoft Windows 10 Enterprise
Connected to the Internet: yes
Connected to VPN: no

**Comment by wfulp** [comment] 2020-09-11 18:17
The issue is with this line:
```
system2("git" ,"remote -v", stdout = TRUE, stderr = FALSE)[1]
```
where Git is not found. This issue is fixed by making sure the cmd folder is in the PATH variable (i.e. `C:\\Program Files\\Git\\cmd`)

**Closed by wfulp** 2020-09-11 18:17 UTC
Labels: bug
